### PR TITLE
Let compiler determine length for fixed-length arrays

### PR DESCRIPTION
**Pull request by Dgame**
Kenji has implemented such a feature in https://github.com/dlang/dmd/pull/3615, but it was rejected afterwards. It's quite usefull.

### CODE REVIEW

**Comment by p0nce** [comment]
Devious and useful! I really like it.

**Comment by Dgame** [comment]
Shall I update the PR?

**Comment by p0nce** [comment]
No need, I always make an editorial pass to check, reword a bit and add author name (I think I should add it in the idiom itself instead of at the bottom)

**Comment by p0nce** [comment]
I've actually repurposed the idiom to show how to have array literals work in @nogc code (something I needed recently!)   https://p0nce.github.io/d-idioms/#@nogc-Array-Literals:-Breaking-the-Limits

**Comment by Dgame** [comment]
I like it. 👍

**Pull request closed without merging**
