### PR TITLE
Rvalue References

### PR DESCRIPTION
**Pull request by Dgame**
A simple way to achieve Rvalue References as in C++

### CODE REVIEW

**Comment by p0nce** [comment]
This is a bit strange because it adds a new field, which is initialized lazily. What if the struct is copied and `this` changes? Is such caching necessary? Seems harmful to me.

I think this need a solution with auto-ref too ideally.

**Comment by Dgame** [comment]
I just came up with an even simpler way. This should be safe:

``` d
mixin template RvalueRef(T) if (is(T == struct))
{
    @nogc @safe
    ref const(T) ByRef() const pure nothrow return
    {
        return this;
    }
}
```

**Comment by p0nce** [comment]
Please correct my understanding:
- this allows to pass literals by reference.
- `auto-ref` can also be used but make template-bloat
- It uses the trick of making a function to get ref values (as parameters or return values).

This is clever and will very probably be merged.

**Comment by Dgame** [comment]
Your understanding is correct.

**Comment by Dgame** [comment]
I've simplified the example.

**Comment by p0nce** [comment]
I'll merge and editorialize in a few days I think. Thanks for the contribution.

**Comment by Dgame** [comment]
My pleasure :)

**Comment by Kozzi11** [comment]
```
ref const(T) byRef(T)() @nogc @safe const pure nothrow return
if (is(T == struct))
{
     return this;
}

struct Vector2f
{
    float x, y;

    this(float x, float y) pure nothrow
    {
        this.x = x;
        this.y = y;
    }
    mixin byRef!(typeof(this));
    //alias byRef this; // do not doo that, it cause compiler to hang :D
}
```

**Comment by p0nce** [comment]
Could it be a free function used with UFCS instead of being mixed in in each struct?

**Comment by Dgame** [comment]
Yes, as one template function with auto ref or as two template functions with one overload for lvalues and one for rvalues. I'll update the PR so that all three ways are covered.

**Comment by Dgame** [comment]
I was wrong. It's only possible with the implementation of DIP1000 which enables the usage of scope. Without that you get an `escaping reference` error.

**Comment by p0nce** [comment]
Still working on a bug fix for customers, so I won't be able to merge it until days.
(EDIT: finally a way for me to understand auto ref!)

**Comment by Dgame** [comment]
No problem, I'm not in a hurry.

**Comment by Dgame** [comment]
Another nice trick with UFCS:

``` d
import std.stdio;

struct Vector2f
{
    float x, y;
}

void invoke(T, U)(auto ref T v, U function(ref T v) f)
{
    f(v);
}

void test(ref const Vector2f v)
{
    writeln(v.x, '|', v.y);
}

void main()
{
    Vector2f(10, 20).invoke(&test);
}
```

Should I add it?

**Comment by p0nce** [comment]
Err, it seems to complicate the entry and the most important I guess it to explain the whole "r-value reference" problem that is discussed in the NG.

**Comment by Dgame** [comment]
Alright. :) Thanks for merging.

**Comment by p0nce** [comment]
How about for the title: "r-value references: understanding `auto ref` and then not using it` ?

**Comment by p0nce** [comment]
I'll add the explanation for auto ref return and params of course, this makes a coherent story.

**Comment by Dgame** [comment]
Sounds good. :) I've just wrote a small & quick explanation myself:
http://forum.dlang.org/post/wleyibdsoxcauozondxh@forum.dlang.org

**Comment by p0nce** [comment]
Is it right to say knowing this trick will avoid many on-stack copies?

**Comment by Dgame** [comment]
Yes, that would be absolutely true. :)

**Comment by p0nce** [comment]
http://p0nce.github.io/d-idioms/#Rvalue-references:-Understanding-auto-ref-and-then-not-using-it

**Comment by Dgame** [comment]
> There are no Rvalue references: Rvalues are copied instead.

In D, RValues will be moved. Only LValues are copied if there is no ref storage class.

**Comment by p0nce** [comment]
I changed the wording. Thanks!

**Comment by Dgame** [comment]
Ok, it looks good now. 👍

**Comment by p0nce** [comment]
I'll do the next PR another day

**Comment by Dgame** [comment]
That's fine, no need to hurry.

**Comment by Dgame** [comment]
I've made progress in outsourcing the rvalue ref conversion:

``` d
import std.stdio;

struct Vector2f
{
    float x, y;
}

void one(ref const Vector2f v)
{
    writeln(v.x, '|', v.y);
}

void two(ref const Vector2f source, ref const Vector2f target)
{
    writefln("From (%.2f|%.2f) to (%.2f|%.2f)", source.x, source.y, target.x, target.y);
}

struct Test
{
    void one(ref const Vector2f v)
    {
        writeln("Test: ", v.x, '|', v.y);
    }

    void two(ref const Vector2f source, ref const Vector2f target)
    {
        writefln("Test: From (%.2f|%.2f) to (%.2f|%.2f)", source.x, source.y, target.x, target.y);
    }
}

void invoke(alias f, V...)(V vs)
{
    f(vs);
}

void invoke(F, V...)(F f, V vs)
{
    f(vs);
}

void main()
{
    invoke!one(Vector2f(10, 20));
    invoke!two(Vector2f(1, 2), Vector2f(3, 4));

    invoke(&one, Vector2f(10, 20));
    invoke(&two, Vector2f(1, 2), Vector2f(3, 4));

    Test t;

    invoke(&t.one, Vector2f(10, 20));
    invoke(&t.two, Vector2f(1, 2), Vector2f(3, 4));
}
```

Should I make a separate PR to add it to the Rvalue chapter? Or do you think it's not worth it?

**Comment by p0nce** [comment]
Sorry I find the `byRef` mixin much cleaner.

**Comment by Dgame** [comment]
Yeah, that's somewhat true.^^

**Pull request merged**
